#index:
#    path: /
#    controller: App\Controller\DefaultController::index

zadanie-1:
  path: /zadanie-1
  controller: App\Controller\TaskOneController::index

zadanie-3:
  path: /zadanie-3
  controller: App\Controller\TaskThreeController::index