#index:
#    path: /
#    controller: App\Controller\DefaultController::index

zadanie-1:
  path: /zadanie-1
  controller: App\Controller\TaskOneController::index

zadanie-2:
  path: /zadanie-2
  controller: App\Controller\TaskTwoController::index